/*
USERNAME: root
PASSWORD: 12345
*/
CREATE TABLE Utente(
id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
username VARCHAR(200) NOT NULL,
name VARCHAR(50),
surname VARCHAR(50),
frase VARCHAR(1024),
email VARCHAR(200),
password VARCHAR(30),
urlImmagineProfilo VARCHAR(1024),
PRIMARY KEY(id,username)
);
/*L'utente deve aver garanzia di loggare nel suo account e non in quello di un'altro con username identico
Username deve essere univoco. In realtà potrei anche non mettere id come campo*/
);
CREATE TABLE Gruppo(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(200) NOT NULL,
description VARCHAR(1024)
);
CREATE TABLE Post(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
content VARCHAR(1024),
id_g INTEGER,
sender INTEGER NOT NULL,
receiver INTEGER , /*SE id_g è settato il receiver è nullo*/
data TIMESTAMP, /*LO DEFINISCO IN TEMESTAMP PER POTER FARE UN SORT SUI POST*/
FOREIGN KEY(id_g) REFERENCES Gruppo(id),
FOREIGN KEY(sender) REFERENCES Utente(id),
FOREIGN KEY(receiver) REFERENCES Utente(id)
);
CREATE TABLE Attached(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
type INTEGER NOT NULL,
path VARCHAR(1024),
id_p INTEGER,
FOREIGN KEY(id_p) REFERENCES Post(id)
);

CREATE TABLE Segue(
follower INTEGER,
   FOREIGN KEY (follower) REFERENCES Utente(id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES Utente(id),
   PRIMARY KEY (follower, followed)
);
CREATE TABLE Appartiene(
id_u INTEGER,
id_g INTEGER,
dataIscrizione VARCHAR(16),
FOREIGN KEY(id_u) REFERENCES Utente(id),
FOREIGN KEY(id_g) REFERENCES Gruppo(id),
PRIMARY KEY(id_u, id_g)
);
/*POPOLAMENTO TABELLE:*/
INSERT INTO Utente (id,username,name,surname,email,password,urlImmagineProfilo)VALUES(default,'Niky','Nikola','Tesla','nikola@gmail.com','abcde','img/Tesla.jpg');
INSERT INTO Utente (id,username,name,surname,frase,email,password,urlImmagineProfilo)VALUES(default,'alb1','Albert','Einstein','E = M*C^2','AEINST@gmail.com','abcde','img/Einstein.jpg');
INSERT INTO Utente (id,username,name,surname,frase,email,password,urlImmagineProfilo)VALUES(default,'Isy','Isaac','Newton','F = m a','ISNEW@gmail.com','abcde','img/Newton.jpg');

INSERT INTO Gruppo VALUES (default,'I Pensionati','Non abbiamo voglia di far niente');
INSERT INTO Gruppo VALUES (default,'Gli sfigati','Racconta a tutti quanta sfiga hai avuto oggi!!');

INSERT INTO Appartiene VALUES(1,2,'10/05/2017-20:06');
INSERT INTO Appartiene (id_u,id_g) VALUES(2,1);
INSERT INTO Appartiene VALUES(3,1,'10/02/1680-15:00');

INSERT INTO Segue VALUES(1,2);
INSERT INTO Segue VALUES(1,3);
INSERT INTO Segue VALUES(2,1);

INSERT INTO Post (content,sender,receiver,data) VALUES ('Questo è un post di prova',1,1,'2017-05-10 21:19:02');
INSERT INTO Post (content,sender,receiver,data) VALUES ('Avevo ragione',2,2,'2017-01-15 11:26:32');
INSERT INTO Post (content,sender,receiver,data) VALUES ('Prova Allegato img',3,3,'2016-06-27 21:53:01');
INSERT INTO Post (content,sender,receiver,data) VALUES ('CIAO ALBERT!!Saluti da Newton',3,2,'2017-03-02 02:32:33');
INSERT INTO Post VALUES(default,'CIAO GRUPPO',1,1,NULL,'2017-04-02 03:35:33.000');

INSERT INTO Attached VALUES(default,1,'img/mela.jpg',3);
INSERT INTO Attached VALUES(default,0,'https://it.wikipedia.org/wiki/Onda_gravitazionale',2);


/*QUERY*/

/*
1)Restituisce l'id dell'utente tramite Username e password

SELECT id
FROM Utente
WHERE username = 'user'
AND password = 'pass' 

2)Restituisce l'utente dato l'id
SELECT *
FROM Utente
WHERE id = id_u
3)Restituisce gli utenti seguiti da un utente con id id_u
SELECT *
FROM Segue s,Utente u
WHERE Follower = id_u 
AND s.Follower = u.id
*/