/*USERNAME: root
  PASSWORD: 12345
*/
CREATE TABLE Utente(
id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
username VARCHAR(200) NOT NULL,
name VARCHAR(50),
surname VARCHAR(50),
frase VARCHAR(1024),
email VARCHAR(200),
password VARCHAR(30),
urlImmagineProfilo VARCHAR(1024),
PRIMARY KEY(id,username)
);
/*L'utente deve aver garanzia di loggare nel suo account e non in quello di un'altro con username identico
Username deve essere univoco. In realtà potrei anche non mettere id come campo*/
);
CREATE TABLE Gruppo(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(200) NOT NULL,
description VARCHAR(1024)
);
CREATE TABLE Post(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
content VARCHAR(1024),
id_g INTEGER,
FOREIGN KEY(id_g) REFERENCES Gruppo(id)
);
CREATE TABLE Attached(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
type INTEGER NOT NULL,
path VARCHAR(1024),
id_p INTEGER,
FOREIGN KEY(id_p) REFERENCES Post(id)
);
CREATE TABLE Scrive(
id_u INTEGER,
id_p INTEGER,
data VARCHAR(16),
/*Ho scelto opportunamente la data da 16 per due motivi:
1# ho solo un campo da analizzare in seguito
2# Posso impostare all'utente che può inserire un solo post al minuto, in quel caso
posso bloccare bot e spam. Infatti se si postano due post nello stesso minuto le chiavi non saranno
più univoche e il db restituirà errore
Formato: GG/MM/AAAA-HH:MM in totale 16 caratteri*/
FOREIGN KEY(id_u) REFERENCES Utente(id),
FOREIGN KEY(id_p) REFERENCES Post(id),
PRIMARY KEY(id_u,id_p,data)
);
CREATE TABLE Segue(
follower INTEGER,
   FOREIGN KEY (follower) REFERENCES Utente(id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES Utente(id),
   PRIMARY KEY (follower, followed)
);
CREATE TABLE Appartiene(
id_u INTEGER,
id_g INTEGER,
dataIscrizione VARCHAR(16),
FOREIGN KEY(id_u) REFERENCES Utente(id),
FOREIGN KEY(id_g) REFERENCES Gruppo(id),
PRIMARY KEY(id_u, id_g)
);
/*POPOLAMENTO TABELLE:*/
INSERT INTO Utente (id,username,name,surname,email,password,urlImmagineProfilo)VALUES(default,'Niky','Nikola','Tesla','nikola@gmail.com','abcde','img/Tesla.jpg');
INSERT INTO Utente (id,username,name,surname,frase,email,password,urlImmagineProfilo)VALUES(default,'alb1','Albert','Einstein','E = M*C^2','AEINST@gmail.com','abcde','img/Einstein.jpg');
INSERT INTO Utente (id,username,name,surname,frase,email,password,urlImmagineProfilo)VALUES(default,'Isy','Isaac','Newton','F = m a','ISNEW@gmail.com','abcde','img/Newton.jpg');

INSERT INTO Gruppo VALUES (default,'I Pensionati','Non abbiamo voglia di far niente');
INSERT INTO Gruppo VALUES (default,'Gli sfigati','Racconta a tutti quanta sfiga hai avuto oggi!!');

INSERT INTO Appartiene VALUES(1,2,'10/05/2017-20:06');
INSERT INTO Appartiene (id_u,id_g) VALUES(2,1);
INSERT INTO Appartiene VALUES(3,1,'10/02/1680-15:00');

INSERT INTO Segue VALUES(1,2);
INSERT INTO Segue VALUES(1,3);
INSERT INTO Segue VALUES(2,1);

INSERT INTO Post (content) VALUES ('Questo è un post di prova');
INSERT INTO Post (content) VALUES ('Avevo ragione');
INSERT INTO Post (content) VALUES ('Prova Allegato img');

INSERT INTO Attached VALUES(default,1,'img/mela.jpg',3);
INSERT INTO Attached VALUES(default,0,'https://it.wikipedia.org/wiki/Onda_gravitazionale',2);

INSERT INTO Scrive VALUES(1,1,'10/05/2017-21:19');
INSERT INTO Scrive VALUES(2,2,'20/03/2011-22:30');
INSERT INTO Scrive VALUES(3,3,'30/06/2011-17:14');